language: php

cache:
    directories:
        - $HOME/.composer/cache

addons:
  apt:
    sources:
      - elasticsearch-2.x
    packages:
      elasticsearch

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION='2.7.*'
    - php: 5.6
      env: SYMFONY_VERSION='2.8.*'
    - php: 5.6
      env: SYMFONY_VERSION='3.0.*'
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - sudo /usr/share/elasticsearch/bin/plugin install -b mapper-attachments
  - sudo service elasticsearch restart
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

services:
  - elasticsearch

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
